package com.aicodequalityrisk.plugin.ui

import com.intellij.ui.JBColor
import java.awt.Color
import java.awt.Dimension

object UIConfig {
    val LICENSE_BANNER_HEIGHT = 36
    val LICENSE_BUTTON_HEIGHT = 28
    val LICENSE_BUTTON_MIN_WIDTH = 80
    val LICENSE_BUTTON_PREFERRED_WIDTH = 120
    val LICENSE_BUTTON_MAX_WIDTH = 200

    val LICENSE_BANNER_MIN = Dimension(100, LICENSE_BANNER_HEIGHT)
    val LICENSE_BANNER_PREFERRED = Dimension(300, LICENSE_BANNER_HEIGHT)
    val LICENSE_BANNER_MAX = Dimension(Short.MAX_VALUE.toInt(), LICENSE_BANNER_HEIGHT)

    val LICENSE_BUTTON_MIN = Dimension(LICENSE_BUTTON_MIN_WIDTH, LICENSE_BUTTON_HEIGHT)
    val LICENSE_BUTTON_PREFERRED = Dimension(LICENSE_BUTTON_PREFERRED_WIDTH, LICENSE_BUTTON_HEIGHT)
    val LICENSE_BUTTON_MAX = Dimension(LICENSE_BUTTON_MAX_WIDTH, LICENSE_BUTTON_HEIGHT)

    val LICENSE_BUTTON_WRAPPER_MIN = Dimension(LICENSE_BUTTON_MIN_WIDTH, LICENSE_BUTTON_HEIGHT)
    val LICENSE_BUTTON_WRAPPER_PREFERRED = Dimension(LICENSE_BUTTON_MAX_WIDTH, LICENSE_BUTTON_HEIGHT)
    val LICENSE_BUTTON_WRAPPER_MAX = Dimension(Short.MAX_VALUE.toInt(), LICENSE_BUTTON_HEIGHT)

    val BANNER_BORDER_LIGHT = Color(200, 180, 150)
    val BANNER_BORDER_DARK = Color(100, 90, 70)

    val LICENSE_ACTIVATED_BG_LIGHT = Color(230, 255, 230)
    val LICENSE_ACTIVATED_BG_DARK = Color(80, 140, 80)
    val LICENSE_ACTIVATED_BG = JBColor(LICENSE_ACTIVATED_BG_LIGHT, LICENSE_ACTIVATED_BG_DARK)

    val LICENSE_EXPIRED_BG_LIGHT = Color(255, 230, 230)
    val LICENSE_EXPIRED_BG_DARK = Color(140, 80, 80)
    val LICENSE_EXPIRED_BG = JBColor(LICENSE_EXPIRED_BG_LIGHT, LICENSE_EXPIRED_BG_DARK)

    val LICENSE_UNLICENSED_BG_LIGHT = Color(255, 245, 230)
    val LICENSE_UNLICENSED_BG_DARK = Color(80, 75, 60)
    val LICENSE_UNLICENSED_BG = JBColor(LICENSE_UNLICENSED_BG_LIGHT, LICENSE_UNLICENSED_BG_DARK)

    val SCORE_GREEN_LIGHT = Color(34, 139, 34)
    val SCORE_GREEN_DARK = Color(60, 179, 113)
    val SCORE_GREEN = JBColor(SCORE_GREEN_LIGHT, SCORE_GREEN_DARK)

    val SCORE_YELLOW_LIGHT = Color(218, 165, 32)
    val SCORE_YELLOW_DARK = Color(255, 215, 0)
    val SCORE_YELLOW = JBColor(SCORE_YELLOW_LIGHT, SCORE_YELLOW_DARK)

    val SCORE_ORANGE_LIGHT = Color(255, 140, 0)
    val SCORE_ORANGE_DARK = Color(255, 165, 0)
    val SCORE_ORANGE = JBColor(SCORE_ORANGE_LIGHT, SCORE_ORANGE_DARK)

    val SCORE_RED_LIGHT = Color(178, 34, 34)
    val SCORE_RED_DARK = Color(205, 92, 92)
    val SCORE_RED = JBColor(SCORE_RED_LIGHT, SCORE_RED_DARK)

    val ACCORDION_HEADER_BG_LIGHT = Color(240, 240, 245)
    val ACCORDION_HEADER_BG_DARK = Color(60, 63, 66)
    val ACCORDION_HEADER_BG = JBColor(ACCORDION_HEADER_BG_LIGHT, ACCORDION_HEADER_BG_DARK)

    val ACCORDION_BORDER_LIGHT = Color(200, 200, 200)
    val ACCORDION_BORDER_DARK = Color(80, 80, 80)
    val ACCORDION_BORDER = JBColor(ACCORDION_BORDER_LIGHT, ACCORDION_BORDER_DARK)

    val TABLE_SELECTED_BG_LIGHT = Color(51, 153, 255)
    val TABLE_SELECTED_BG_DARK = Color(80, 80, 80)
    val TABLE_SELECTED_BG = JBColor(TABLE_SELECTED_BG_LIGHT, TABLE_SELECTED_BG_DARK)

    val TABLE_SEVERITY_FALLBACK_LIGHT = Color.LIGHT_GRAY
    val TABLE_SEVERITY_FALLBACK_DARK = Color.darkGray
    val TABLE_SEVERITY_FALLBACK = JBColor(TABLE_SEVERITY_FALLBACK_LIGHT, TABLE_SEVERITY_FALLBACK_DARK)
}