package com.aicodequalityrisk.plugin.ui

import java.awt.Dimension

object UIConfig {
    val LICENSE_BANNER_HEIGHT = 36
    val LICENSE_BUTTON_HEIGHT = 28
    val LICENSE_BUTTON_MIN_WIDTH = 80
    val LICENSE_BUTTON_PREFERRED_WIDTH = 120
    val LICENSE_BUTTON_MAX_WIDTH = 200

    val LICENSE_BANNER_MIN = Dimension(200, LICENSE_BANNER_HEIGHT)
    val LICENSE_BANNER_PREFERRED = Dimension(300, LICENSE_BANNER_HEIGHT)
    val LICENSE_BANNER_MAX = Dimension(Short.MAX_VALUE.toInt(), LICENSE_BANNER_HEIGHT)

    val LICENSE_BUTTON_MIN = Dimension(LICENSE_BUTTON_MIN_WIDTH, LICENSE_BUTTON_HEIGHT)
    val LICENSE_BUTTON_PREFERRED = Dimension(LICENSE_BUTTON_PREFERRED_WIDTH, LICENSE_BUTTON_HEIGHT)
    val LICENSE_BUTTON_MAX = Dimension(LICENSE_BUTTON_MAX_WIDTH, LICENSE_BUTTON_HEIGHT)

    val LICENSE_BUTTON_WRAPPER_MIN = Dimension(LICENSE_BUTTON_MIN_WIDTH, LICENSE_BUTTON_HEIGHT)
    val LICENSE_BUTTON_WRAPPER_PREFERRED = Dimension(LICENSE_BUTTON_MAX_WIDTH, LICENSE_BUTTON_HEIGHT)
    val LICENSE_BUTTON_WRAPPER_MAX = Dimension(Short.MAX_VALUE.toInt(), LICENSE_BUTTON_HEIGHT)
}